// <auto-generated />
using System;
using AquaScale.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AquaScale.Api.Migrations
{
    [DbContext(typeof(AquaScaleDbContext))]
    [Migration("20260725051534_AddMeterStubForMirrorJoinTest")]
    partial class AddMeterStubForMirrorJoinTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.BillingStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("CurrentCharge")
                        .HasColumnType("numeric")
                        .HasColumnName("current_charge");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("MeterReadingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_reading_id");

                    b.Property<decimal?>("Penalty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasColumnName("penalty")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("PreviousBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasColumnName("previous_balance")
                        .HasDefaultValueSql("0");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Draft'::text");

                    b.Property<Guid?>("SupersededBy")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by");

                    b.Property<decimal>("TotalAmountDue")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount_due");

                    b.Property<string>("UtilityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("utility_type");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at");

                    b.Property<Guid?>("WebsConsumptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("webs_consumption_id");

                    b.Property<int?>("WebsSeqNo")
                        .HasColumnType("integer")
                        .HasColumnName("webs_seq_no");

                    b.Property<string>("WebsSyncError")
                        .HasColumnType("text")
                        .HasColumnName("webs_sync_error");

                    b.Property<string>("WebsSyncStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("webs_sync_status")
                        .HasDefaultValueSql("'Pending'::text");

                    b.HasKey("Id")
                        .HasName("billing_statements_pkey");

                    b.ToTable("billing_statements", (string)null);
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Meter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("MirrorAcctmtrId")
                        .HasColumnType("uuid")
                        .HasColumnName("mirror_acctmtr_id");

                    b.HasKey("Id")
                        .HasName("pk_meters");

                    b.HasIndex("MirrorAcctmtrId")
                        .HasDatabaseName("ix_meters_mirror_acctmtr_id");

                    b.ToTable("meters", (string)null);
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BuyerRef")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_ref");

                    b.Property<string>("ContactNo")
                        .HasColumnType("text")
                        .HasColumnName("contact_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateDeactivated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_deactivated");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_profiles_role_id");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("AquaScale.Api.Models.Mirror.MirrorAccountMeter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNo")
                        .HasColumnType("text")
                        .HasColumnName("account_no");

                    b.Property<string>("Createdby")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateEdited")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_edited");

                    b.Property<DateTime?>("DateInstalled")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_installed");

                    b.Property<decimal?>("DepAmt")
                        .HasColumnType("numeric")
                        .HasColumnName("dep_amt");

                    b.Property<DateTime?>("DepDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dep_date");

                    b.Property<string>("Editedby")
                        .HasColumnType("text")
                        .HasColumnName("editedby");

                    b.Property<string>("MeterNo")
                        .HasColumnType("text")
                        .HasColumnName("meter_no");

                    b.Property<string>("MeterStatus")
                        .HasColumnType("text")
                        .HasColumnName("meter_status");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_date");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("Id")
                        .HasName("pk_mirror_account_meters");

                    b.ToTable("mirror_account_meters", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Meter", b =>
                {
                    b.HasOne("AquaScale.Api.Models.Mirror.MirrorAccountMeter", "MirrorAccountMeter")
                        .WithMany()
                        .HasForeignKey("MirrorAcctmtrId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_meters_mirror_account_meters_mirror_acctmtr_id");

                    b.Navigation("MirrorAccountMeter");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Profile", b =>
                {
                    b.HasOne("AquaScale.Api.Models.AquaScale.Role", "Role")
                        .WithMany("Profiles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profiles_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.RolePermission", b =>
                {
                    b.HasOne("AquaScale.Api.Models.AquaScale.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("AquaScale.Api.Models.AquaScale.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Role", b =>
                {
                    b.Navigation("Profiles");

                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
