// <auto-generated />
using System;
using AquaScale.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AquaScale.Api.Migrations
{
    [DbContext(typeof(AquaScaleDbContext))]
    [Migration("20260805123825_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.BillingStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal>("CurrentCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MeterReadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Penalty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("PreviousBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValueSql("0");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("'Draft'");

                    b.Property<Guid?>("SupersededBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmountDue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UtilityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("WebsConsumptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("WebsSeqNo")
                        .HasColumnType("int");

                    b.Property<string>("WebsSyncError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsSyncStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("'Pending'");

                    b.HasKey("Id");

                    b.ToTable("BillingStatements");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Meter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateMarkedNonOperational")
                        .HasColumnType("datetime2");

                    b.Property<int>("MeterStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("MirrorAcctmtrId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QrCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtilityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Meters");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.MeterReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("FieldWorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("GpsLat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GpsLng")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDuplicateFlag")
                        .HasColumnType("bit");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("OcrReadingValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PreviousReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QrScannedCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecaptureCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SecondsSinceLastCapture")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FieldWorkerId");

                    b.HasIndex("MeterId");

                    b.HasIndex("ReviewedBy");

                    b.ToTable("MeterReadings");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuyerRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Block")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompPbl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Lot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MirrorAccountNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubdivisionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubdivisionId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Subdivision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeojsonBoundary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MobileDataProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subdivisions");
                });

            modelBuilder.Entity("AquaScale.Api.Models.Webs.WEBSAccountMeter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateInstalled")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DepAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DepDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Hold")
                        .HasColumnType("bit");

                    b.Property<string>("MeterNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeterStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("WithIssue")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("T_Account_Meter", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AquaScale.Api.Models.Webs.WEBSBillingAccount", b =>
                {
                    b.Property<string>("AccountNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcctStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateReg")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entity_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Movein")
                        .HasColumnType("datetime2");

                    b.Property<string>("Project_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReservationNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountNo");

                    b.ToTable("T_Billing_Account", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AquaScale.Api.Models.Webs.WEBSBuyer", b =>
                {
                    b.Property<string>("BuyerId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Buyer_ID");

                    b.Property<string>("BuyerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuyerId");

                    b.ToTable("M_Buyer", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AquaScale.Api.Models.Webs.WEBSBuyerContact", b =>
                {
                    b.Property<string>("BuyerId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Buyer_ID");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuyerId", "DateUpdated");

                    b.ToTable("M_Buyer_Contact", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AquaScale.Api.Models.Webs.WEBSConsumption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcctMtrId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AcctMtr_ID");

                    b.Property<decimal>("CurCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("CurRead")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateRead")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("PrevRead")
                        .HasColumnType("float");

                    b.Property<decimal>("RatePerMtr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeqNo")
                        .HasColumnType("int");

                    b.Property<double>("UsedPerMtr")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("T_Consumption", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AquaScale.Api.Models.Webs.WEBSPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcctMtrId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AcctMtr_ID");

                    b.Property<decimal?>("AmtPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OrDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ORDate");

                    b.Property<string>("OrNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Penalty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrevBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeqNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotAmtDue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("T_Payment", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AquaScale.Api.Models.Webs.WEBSReservation", b =>
                {
                    b.Property<string>("ReservationNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BackoutType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Buyer_ID");

                    b.Property<string>("CompPBL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateReserved")
                        .HasColumnType("datetime2");

                    b.HasKey("ReservationNo");

                    b.ToTable("T_PM_Reservation", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Meter", b =>
                {
                    b.HasOne("AquaScale.Api.Models.AquaScale.Property", "Property")
                        .WithMany("Meters")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.MeterReading", b =>
                {
                    b.HasOne("AquaScale.Api.Models.AquaScale.Profile", "FieldWorker")
                        .WithMany()
                        .HasForeignKey("FieldWorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AquaScale.Api.Models.AquaScale.Meter", "Meter")
                        .WithMany("MeterReadings")
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AquaScale.Api.Models.AquaScale.Profile", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FieldWorker");

                    b.Navigation("Meter");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Profile", b =>
                {
                    b.HasOne("AquaScale.Api.Models.AquaScale.Role", "Role")
                        .WithMany("Profiles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Property", b =>
                {
                    b.HasOne("AquaScale.Api.Models.AquaScale.Subdivision", "Subdivision")
                        .WithMany("Properties")
                        .HasForeignKey("SubdivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subdivision");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.RolePermission", b =>
                {
                    b.HasOne("AquaScale.Api.Models.AquaScale.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AquaScale.Api.Models.AquaScale.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Meter", b =>
                {
                    b.Navigation("MeterReadings");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Property", b =>
                {
                    b.Navigation("Meters");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Role", b =>
                {
                    b.Navigation("Profiles");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Subdivision", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
