// <auto-generated />
using System;
using AquaScale.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AquaScale.Api.Migrations
{
    [DbContext(typeof(AquaScaleDbContext))]
    partial class AquaScaleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.BillingStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("CurrentCharge")
                        .HasColumnType("numeric")
                        .HasColumnName("current_charge");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("MeterReadingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_reading_id");

                    b.Property<decimal?>("Penalty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasColumnName("penalty")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("PreviousBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasColumnName("previous_balance")
                        .HasDefaultValueSql("0");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Draft'::text");

                    b.Property<Guid?>("SupersededBy")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by");

                    b.Property<decimal>("TotalAmountDue")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount_due");

                    b.Property<string>("UtilityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("utility_type");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at");

                    b.Property<Guid?>("WebsConsumptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("webs_consumption_id");

                    b.Property<int?>("WebsSeqNo")
                        .HasColumnType("integer")
                        .HasColumnName("webs_seq_no");

                    b.Property<string>("WebsSyncError")
                        .HasColumnType("text")
                        .HasColumnName("webs_sync_error");

                    b.Property<string>("WebsSyncStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("webs_sync_status")
                        .HasDefaultValueSql("'Pending'::text");

                    b.HasKey("Id")
                        .HasName("billing_statements_pkey");

                    b.ToTable("billing_statements", (string)null);
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Meter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateMarkedNonOperational")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_marked_non_operational");

                    b.Property<int>("MeterStatus")
                        .HasColumnType("integer")
                        .HasColumnName("meter_status");

                    b.Property<Guid?>("MirrorAcctmtrId")
                        .HasColumnType("uuid")
                        .HasColumnName("mirror_acctmtr_id");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("QrCode")
                        .HasColumnType("text")
                        .HasColumnName("qr_code");

                    b.Property<string>("UtilityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("utility_type");

                    b.HasKey("Id")
                        .HasName("pk_meters");

                    b.HasIndex("MirrorAcctmtrId")
                        .HasDatabaseName("ix_meters_mirror_acctmtr_id");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_meters_property_id");

                    b.ToTable("meters", (string)null);
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.MeterReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence_score");

                    b.Property<Guid>("FieldWorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("field_worker_id");

                    b.Property<decimal?>("GpsLat")
                        .HasColumnType("numeric")
                        .HasColumnName("gps_lat");

                    b.Property<decimal?>("GpsLng")
                        .HasColumnType("numeric")
                        .HasColumnName("gps_lng");

                    b.Property<bool>("IsDuplicateFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("is_duplicate_flag");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_id");

                    b.Property<decimal?>("OcrReadingValue")
                        .HasColumnType("numeric")
                        .HasColumnName("ocr_reading_value");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<decimal?>("PreviousReading")
                        .HasColumnType("numeric")
                        .HasColumnName("previous_reading");

                    b.Property<string>("QrScannedCode")
                        .HasColumnType("text")
                        .HasColumnName("qr_scanned_code");

                    b.Property<int>("RecaptureCount")
                        .HasColumnType("integer")
                        .HasColumnName("recapture_count");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<int?>("SecondsSinceLastCapture")
                        .HasColumnType("integer")
                        .HasColumnName("seconds_since_last_capture");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_meter_readings");

                    b.HasIndex("FieldWorkerId")
                        .HasDatabaseName("ix_meter_readings_field_worker_id");

                    b.HasIndex("MeterId")
                        .HasDatabaseName("ix_meter_readings_meter_id");

                    b.HasIndex("ReviewedBy")
                        .HasDatabaseName("ix_meter_readings_reviewed_by");

                    b.ToTable("meter_readings", (string)null);
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BuyerRef")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_ref");

                    b.Property<string>("ContactNo")
                        .HasColumnType("text")
                        .HasColumnName("contact_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateDeactivated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_deactivated");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_profiles_role_id");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Block")
                        .HasColumnType("text")
                        .HasColumnName("block");

                    b.Property<string>("CompPbl")
                        .HasColumnType("text")
                        .HasColumnName("comp_pbl");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("Lot")
                        .HasColumnType("text")
                        .HasColumnName("lot");

                    b.Property<string>("MirrorAccountNo")
                        .HasColumnType("text")
                        .HasColumnName("mirror_account_no");

                    b.Property<Guid>("SubdivisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subdivision_id");

                    b.HasKey("Id")
                        .HasName("pk_properties");

                    b.HasIndex("SubdivisionId")
                        .HasDatabaseName("ix_properties_subdivision_id");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Subdivision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GeojsonBoundary")
                        .HasColumnType("text")
                        .HasColumnName("geojson_boundary");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MobileDataProvider")
                        .HasColumnType("text")
                        .HasColumnName("mobile_data_provider");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_subdivisions");

                    b.ToTable("subdivisions", (string)null);
                });

            modelBuilder.Entity("AquaScale.Api.Models.Mirror.MirrorAccountMeter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNo")
                        .HasColumnType("text")
                        .HasColumnName("account_no");

                    b.Property<string>("Createdby")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateEdited")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_edited");

                    b.Property<DateTime?>("DateInstalled")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_installed");

                    b.Property<decimal?>("DepAmt")
                        .HasColumnType("numeric")
                        .HasColumnName("dep_amt");

                    b.Property<DateTime?>("DepDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dep_date");

                    b.Property<string>("Editedby")
                        .HasColumnType("text")
                        .HasColumnName("editedby");

                    b.Property<string>("MeterNo")
                        .HasColumnType("text")
                        .HasColumnName("meter_no");

                    b.Property<string>("MeterStatus")
                        .HasColumnType("text")
                        .HasColumnName("meter_status");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_date");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("Id")
                        .HasName("pk_mirror_account_meters");

                    b.ToTable("mirror_account_meters", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Meter", b =>
                {
                    b.HasOne("AquaScale.Api.Models.Mirror.MirrorAccountMeter", "MirrorAccountMeter")
                        .WithMany()
                        .HasForeignKey("MirrorAcctmtrId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_meters_mirror_account_meters_mirror_acctmtr_id");

                    b.HasOne("AquaScale.Api.Models.AquaScale.Property", "Property")
                        .WithMany("Meters")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meters_properties_property_id");

                    b.Navigation("MirrorAccountMeter");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.MeterReading", b =>
                {
                    b.HasOne("AquaScale.Api.Models.AquaScale.Profile", "FieldWorker")
                        .WithMany()
                        .HasForeignKey("FieldWorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meter_readings_profiles_field_worker_id");

                    b.HasOne("AquaScale.Api.Models.AquaScale.Meter", "Meter")
                        .WithMany("MeterReadings")
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meter_readings_meters_meter_id");

                    b.HasOne("AquaScale.Api.Models.AquaScale.Profile", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_meter_readings_profiles_reviewed_by");

                    b.Navigation("FieldWorker");

                    b.Navigation("Meter");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Profile", b =>
                {
                    b.HasOne("AquaScale.Api.Models.AquaScale.Role", "Role")
                        .WithMany("Profiles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profiles_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Property", b =>
                {
                    b.HasOne("AquaScale.Api.Models.AquaScale.Subdivision", "Subdivision")
                        .WithMany("Properties")
                        .HasForeignKey("SubdivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_properties_subdivisions_subdivision_id");

                    b.Navigation("Subdivision");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.RolePermission", b =>
                {
                    b.HasOne("AquaScale.Api.Models.AquaScale.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("AquaScale.Api.Models.AquaScale.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Meter", b =>
                {
                    b.Navigation("MeterReadings");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Property", b =>
                {
                    b.Navigation("Meters");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Role", b =>
                {
                    b.Navigation("Profiles");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("AquaScale.Api.Models.AquaScale.Subdivision", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
