using System.ComponentModel.DataAnnotations;

namespace AquaScale.Api.Models.Webs;

/// <summary>
/// Maps to WEBS.dbo.M_ControlNo — manual sequence number generator.
/// WEBS does NOT use SQL IDENTITY. All transaction numbers (ORNo, ConsumptionNo, etc.)
/// are generated by reading this table, incrementing last_series_no, and saving back.
/// 
/// CRITICAL RULE: Never configure any PK in the WEBS models as DatabaseGenerated(Identity).
/// This table IS the identity mechanism for WEBS.
///
/// control_id is the logical row identifier. All columns are nullable in WEBS schema.
/// Configured with HasKey(e => e.ControlId) + ValueGeneratedNever() in WebsDbContext.
/// Schema validated against WEBS-Schema.txt.
///
/// Usage: SELECT and UPDATE last_series_no within a transaction, then format the number
/// using data_width (zero-padded) and the mode/year/period affixes.
/// </summary>
public class WEBSControlNo
{
    public int?     ControlId     { get; set; }  // control_id int NULL — logical key
    [MaxLength(15)]
    public string?  ControlType   { get; set; }  // control_type varchar(15) NULL — e.g. "OR", "CONS"
    [MaxLength(50)]
    public string?  ControlDesc   { get; set; }  // control_desc varchar(50) NULL
    [MaxLength(10)]
    public string?  ControlCoId   { get; set; }  // control_co_id varchar(10) NULL — company filter
    [MaxLength(1)]
    public string?  ControlMode   { get; set; }  // control_mode varchar(1) NULL
    [MaxLength(2)]
    public string?  ControlYear   { get; set; }  // control_year varchar(2) NULL — 2-digit year affix
    [MaxLength(2)]
    public string?  ControlPeriod { get; set; }  // control_period varchar(2) NULL — month/period affix
    public int?     DataWidth     { get; set; }  // data_width int NULL — zero-pad width for series
    public int?     LastSeriesNo  { get; set; }  // last_series_no int NULL — increment this and save
    [MaxLength(1)]
    public string?  StatusId      { get; set; }  // status_id varchar(1) NULL
}
